clear; clc;
% define figure properties
opts.width      = 15;
opts.height     = 8;
opts.fontType   = 'Times';
opts.fontSize   = 10;

% Number of Local Maximum Power Points under PSCs
fig = figure;
LMPPs = [5 4 4 2 5 6];
spider_plot(LMPPs,...
    'AxesLabels', {'Center', 'Corner', 'Diagonal', 'Frame', 'Random', 'Right Side'},...
    'AxesInterval', 6,...
    'AxesPrecision', 0,...
    'AxesDisplay', 'one',...
    'AxesOffset', 0,...
    'AxesLabelsOffset', 0.17,...
    'AxesHorzAlign', 'left',...
    'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
    'AxesFontSize', 10,...
    'LabelFontSize', 10,...
    'Color', '[0.5 0 1]',...
    'AxesLabelsEdge', 'none',...
    'AxesColor', [0.85, 0.85, 0.85],...
    'AxesLimits', [0, 0, 0, 0, 0, 0; 7, 7, 7, 7, 7, 7]);
% scaling
fig.Units               = 'centimeters';
fig.Position(3)         = opts.width;
fig.Position(4)         = opts.height;
% set text properties
set(fig.Children, ...
    'FontName',     opts.fontType, ...
    'FontSize',     opts.fontSize);
% remove unnecessary white space
set(gca,'LooseInset',max(get(gca,'TightInset'), 0.02))
% export to png
fig.PaperPositionMode   = 'auto';
print('Number of Local Maximum Power Points under PSCs', '-dpng', '-r600')